### ISSUE TITLE
5.5.1 中的一处问题

### ISSUE THREAD

**Issue by hhelibeb** [jeffreybaoshenlee/zh-translation-errata-sysarch#10]
5.5.1 功能交互与功能架构， 最后一句话，

> 在这种简单的流式系统中，有一种**非常特殊**的操作数，它由上游的过程所创建，并且由下游的过程来销毁，这种操作数构成了交互。

”一种非常特殊的操作数“的意思很难理解。原文为，

> In such simple flow-through systems, there is a **unique** operand that is created by the upstream process and destroyed by the downstream process, which constitutes the interaction.

原文中的unique，应为”唯一“的意思。

这段话的意思是说，简单系统中的上下游过程交互只涉及唯一的操作数，由上游过程创建并由下游过程销毁。如下图所示，
![图片](https://user-images.githubusercontent.com/16676760/70292759-fb71a700-1819-11ea-92a7-a09a293b455b.png)
<center>(Figure 5.12 internal functions and functional architecture of bread slice making.)</center>
<br/>

请看看我的理解是否正确，谢谢！

**Comment by jeffreybaoshenlee** [comment]
@hhelibeb   嗯，感谢您指出这个问题，我已经记录到勘误表（https://github.com/jeffreybaoshenlee/zh-translation-errata-sysarch/issues/9 ）了，期望再版时能够更正。多谢指教。
