### ISSUE TITLE
13.2的一处内容，需要讨论

### ISSUE THREAD

**Issue by hhelibeb** [jeffreybaoshenlee/zh-translation-errata-sysarch#11]
译文：
> 对复杂度的定义方式达成共识之后，复杂度就成了系统中一项可以量化的绝对属性了。无论是采用笔者所推荐的简单定义， 还是另选一种其他的定义方式，我们都认为复 杂度应该当成一个可以度量的值。它不应该视为设计过程的成果， 而是应该视为一种需要管理的量。根据笔者的经验： **如果把复杂度看作一种难以应付的东西，那么它就更有可能会遭到忽视，这样反而又增加了复杂度**。

“如果把复杂度看作一种难以应付的东西，那么它就更有可能会遭到忽视，这样反而又增加了复杂度”不是很好理解。为什么忽视复杂度会导致复杂度增加？

原文：
> Complexity is an absolute and quantifiable system property, once a definition is agreed upon.  Regardless of whether our simple definition or another definition is chosen, we believe that it is  valuable to regard complexity as a measurable quantity. Complexity should not be viewed as an outcome of the design process, but rather as a quantity to be managed. Our experience suggests that **when complexity is viewed as an intractable topic, it is more likely to be ignored, at the cost of increased complexity**!

其中，at the cost of increased complexity中的at似乎并无“产生、导致”的意思。相反，at有“由于、因为”的意思。
参考剑桥词典：
> used to show the cause of something, especially a feeling
（尤指感觉是）由于，因为，作为对…的反应
We were surprised at the news. 我们听到这个消息很吃惊。
I was quite excited at the prospect. 想到这种前景，我激动不已。
Why does no one ever laugh at my jokes? 为什么我讲了笑话，从来就没人笑呢？

综上，这句话的意思应当为：
“如果把复杂度看作一种难以应付的东西（设计过程的结果），那么由于（设计过程的结果会比可度量的值带来）更多的复杂度开销，它就更有可能会遭到忽视”。

@jeffreybaoshenlee 请看看我的想法是否正确，谢谢！

**Comment by jeffreybaoshenlee** [comment]
嗯，感谢您指出这个问题。我当时的译文说得不够清楚，现在修改如下：

_如果你总是觉得复杂度难于应付，那就有可能干脆忽视它，而不去认真地给它做量化，这样反倒会让项目变得更加复杂。_

这里我是把“at the cost of ...”这个短语合起来理解成“以……为代价”，而不单独对译其中的 at。（以增加项目的复杂度为代价，来逃避对复杂度做量化这一困难的任务）

我已经把这个错误添加到勘误表（https://github.com/jeffreybaoshenlee/zh-translation-errata-sysarch/issues/9#issue-444575973 ）了，希望再版时得到修正。 @hhelibeb

**Comment by hhelibeb** [comment]
> 
> 
> 嗯，感谢您指出这个问题。我当时的译文说得不够清楚，现在修改如下：
> 
> _如果你总是觉得复杂度难于应付，那就有可能干脆忽视它，而不去认真地给它做量化，这样反倒会让项目变得更加复杂。_
> 
> 这里我是把“at the cost of ...”这个短语合起来理解成“以……为代价”，而不单独对译其中的 at。（以增加项目的复杂度为代价，来逃避对复杂度做量化这一困难的任务）
> 
> 我已经把这个错误添加到勘误表（[#9 (comment)](https://github.com/jeffreybaoshenlee/zh-translation-errata-sysarch/issues/9#issue-444575973) ）了，希望再版时得到修正。 @hhelibeb

明白了，谢谢指点
